<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width">
    <title>@section('header')@endsection</title>
    @php
        $linkColor="#F76613";
    @endphp
    <!-- this partial includes custom css that is used in some templates on site, but not present in this repository, so it is stripped during inlining  -->
    @include('my.email.partials.styles')
</head>
<body style="-moz-box-sizing:border-box;-ms-text-size-adjust:100%;-webkit-box-sizing:border-box;-webkit-text-size-adjust:100%;Margin:0;box-sizing:border-box;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:300;line-height:1.2;margin:0;min-width:100%;padding:0;text-align:left;width:100%!important">
<span class="preheader" style="color:#f3f3f3;display:none!important;font-size:1px;line-height:1px;max-height:0;max-width:0;mso-hide:all!important;opacity:0;overflow:hidden;visibility:hidden">@yield('header')</span>
<table class="body" style="Margin:0;background:#f3f3f3;border-collapse:collapse;border-spacing:0;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:300;height:100%;line-height:1.2;margin:0;padding:0;text-align:left;vertical-align:top;width:100%">
    <tr style="padding:0;text-align:left;vertical-align:top">
        <td class="center" align="center" valign="top" style="-moz-hyphens:auto;-webkit-hyphens:auto;Margin:0;border-collapse:collapse!important;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:300;hyphens:auto;line-height:1.2;margin:0;padding:0;text-align:left;vertical-align:top;word-wrap:break-word">
            <center data-parsed="" style="min-width:680px;width:100%">
                <table class="spacer float-center" style="Margin:0 auto;border-collapse:collapse;border-spacing:0;float:none;margin:0 auto;padding:0;text-align:center;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top"><td height="16px" style="-moz-hyphens:auto;-webkit-hyphens:auto;Margin:0;border-collapse:collapse!important;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:16px;font-weight:300;hyphens:auto;line-height:16px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-wrap:break-word"></td></tr></tbody></table>
                <table align="center" class="container float-center" style="Margin:0 auto;background:#fefefe;border-collapse:collapse;border-spacing:0;box-shadow:0 1px 3px rgba(0,0,0,.12),0 1px 2px rgba(0,0,0,.24);float:none;margin:0 auto;padding:0;text-align:center;vertical-align:top;width:680px"><tbody><tr style="padding:0;text-align:left;vertical-align:top"><td style="-moz-hyphens:auto;-webkit-hyphens:auto;Margin:0;border-collapse:collapse!important;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:300;hyphens:auto;line-height:1.2;margin:0;padding:0;text-align:left;vertical-align:top;word-wrap:break-word">
                            <table class="row header cr-header cr-header--secondary bottom-bordered" style="background:#fefefe;border-bottom:1px solid #F76613;border-collapse:collapse;border-spacing:0;display:table;padding:0;position:relative;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top">
                                    <th class="small-12 large-12 columns first last" style="Margin:0 auto;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:400;line-height:1.2;margin:0 auto;padding:0;padding-bottom:0;padding-left:30px;padding-right:30px;text-align:left;width:650px"><table style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tr style="padding:0;text-align:left;vertical-align:top"><th style="Margin:0;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:400;line-height:1.2;margin:0;padding:0;text-align:left">
                                                    <table class="row" style="border-collapse:collapse;border-spacing:0;display:table;padding:0;position:relative;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top">
                                                            <th class="small-12 large-12 columns first last" style="Margin:0 auto;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:400;line-height:1.2;margin:0 auto;padding:0;padding-bottom:0;padding-left:0!important;padding-right:0!important;text-align:left;width:100%"><table style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tr style="padding:0;text-align:left;vertical-align:top"><th style="Margin:0;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:400;line-height:1.2;margin:0;padding:0;text-align:left">
                                                                            <table class="spacer" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top"><td height="8px" style="-moz-hyphens:auto;-webkit-hyphens:auto;Margin:0;border-collapse:collapse!important;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:8px;font-weight:300;hyphens:auto;line-height:8px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-wrap:break-word"></td></tr></tbody></table>
                                                                        </th>
                                                                        <th class="expander" style="Margin:0;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:400;line-height:1.2;margin:0;padding:0!important;text-align:left;visibility:hidden;width:0"></th></tr></table></th>
                                                        </tr></tbody></table>
                                                    <table class="row" style="border-collapse:collapse;border-spacing:0;display:table;padding:0;position:relative;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top">
                                                            <th class="small-12 large-12 columns first last" style="Margin:0 auto;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:400;line-height:1.2;margin:0 auto;padding:0;padding-bottom:0;padding-left:0!important;padding-right:0!important;text-align:left;width:100%"><table style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tr style="padding:0;text-align:left;vertical-align:top"><th style="Margin:0;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:400;line-height:1.2;margin:0;padding:0;text-align:left">
                                                                            <!--                    this is /src/assets/img/cloudradar_logo_big.png inlined-->
                                                                            <img width="376" height="66" style="-ms-interpolation-mode:bicubic;clear:both;color:#fefefe;display:block;float:left;font-family:Helvetica,Arial,sans-serif;font-size:24px;font-weight:400;height:66px;line-height:1;max-width:100%;outline:0;text-align:left;text-decoration:none;width:376px" alt="CloudRadar Logo" class="float-left logo" src="{{ $message->embed('public/assets/images/marketing/cloudradar_logo_big.png') }}">
                                                                        </th>
                                                                        <th class="expander" style="Margin:0;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:400;line-height:1.2;margin:0;padding:0!important;text-align:left;visibility:hidden;width:0"></th></tr></table></th>
                                                        </tr></tbody></table>
                                                    <table class="row" style="border-collapse:collapse;border-spacing:0;display:table;padding:0;position:relative;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top">
                                                            <th class="small-12 large-12 columns first last" style="Margin:0 auto;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:400;line-height:1.2;margin:0 auto;padding:0;padding-bottom:0;padding-left:0!important;padding-right:0!important;text-align:left;width:100%"><table style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tr style="padding:0;text-align:left;vertical-align:top"><th style="Margin:0;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:400;line-height:1.2;margin:0;padding:0;text-align:left">
                                                                            <table class="spacer" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top"><td height="8px" style="-moz-hyphens:auto;-webkit-hyphens:auto;Margin:0;border-collapse:collapse!important;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:8px;font-weight:300;hyphens:auto;line-height:8px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-wrap:break-word"></td></tr></tbody></table>
                                                                        </th>
                                                                        <th class="expander" style="Margin:0;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:400;line-height:1.2;margin:0;padding:0!important;text-align:left;visibility:hidden;width:0"></th></tr></table></th>
                                                        </tr></tbody></table>
                                                </th></tr></table></th>
                                </tr></tbody></table>
                            <table class="row bottom-bordered" style="border-bottom:1px solid #F76613;border-collapse:collapse;border-spacing:0;display:table;padding:0;position:relative;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top">
                                    <th class="small-12 large-12 columns first last" style="Margin:0 auto;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:400;line-height:1.2;margin:0 auto;padding:0;padding-bottom:16px;padding-left:30px;padding-right:30px;text-align:left;width:650px"><table style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tr style="padding:0;text-align:left;vertical-align:top"><th style="Margin:0;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:400;line-height:1.2;margin:0;padding:0;text-align:left">
                                                    <table class="spacer" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top"><td height="32px" style="-moz-hyphens:auto;-webkit-hyphens:auto;Margin:0;border-collapse:collapse!important;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:32px;font-weight:300;hyphens:auto;line-height:32px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-wrap:break-word"></td></tr></tbody></table>
                                                    <h1 style="Margin:0;Margin-bottom:10px;color:inherit;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:18pt;font-weight:500;line-height:1.2;margin:0;margin-bottom:10px;padding:0;text-align:left;word-wrap:normal">
                                                        @yield('header')
                                                    </h1>
                                                    @yield('text')
                                                    <table class="spacer" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top"><td height="8px" style="-moz-hyphens:auto;-webkit-hyphens:auto;Margin:0;border-collapse:collapse!important;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:8px;font-weight:300;hyphens:auto;line-height:8px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-wrap:break-word"></td></tr></tbody></table>
                                                </th>
                                                <th class="expander" style="Margin:0;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:400;line-height:1.2;margin:0;padding:0!important;text-align:left;visibility:hidden;width:0"></th></tr></table></th>
                                </tr></tbody></table>
                            <table class="row" style="border-collapse:collapse;border-spacing:0;display:table;padding:0;position:relative;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top">
                                    <th class="small-12 large-12 columns first last" style="Margin:0 auto;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:400;line-height:1.2;margin:0 auto;padding:0;padding-bottom:16px;padding-left:30px;padding-right:30px;text-align:left;width:650px"><table style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tr style="padding:0;text-align:left;vertical-align:top"><th style="Margin:0;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:400;line-height:1.2;margin:0;padding:0;text-align:left">
                                                    <table class="spacer" style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top"><td height="8px" style="-moz-hyphens:auto;-webkit-hyphens:auto;Margin:0;border-collapse:collapse!important;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:8px;font-weight:300;hyphens:auto;line-height:8px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-wrap:break-word"></td></tr></tbody></table>
                                                    <p style="Margin:0;Margin-bottom:10px;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:300;line-height:1.2;margin:0;margin-bottom:10px;padding:0;text-align:left">
                                                        <small style="color:#8a8a8a;font-size:8pt">@yield('unsubscribe')</small>
                                                    </p>
                                                    <p style="Margin:0;Margin-bottom:10px;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:300;line-height:1.2;margin:0;margin-bottom:10px;padding:0;text-align:left">
                                                        <small style="color:#8a8a8a;font-size:8pt">
                                                            CloudRadar GmbH<br>
                                                            <a class="footer-link" href="https://www.cloudradar.io" target="_blank" rel="noopener noreferrer" style="Margin:0;color:#8a8a8a;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-weight:500;line-height:1.2;margin:0;padding:0;text-align:left;text-decoration:none">www.cloudradar.io</a><br>
                                                            <a class="footer-link" href="mailto:support@cloudradar.io" target="_blank" rel="noopener noreferrer" style="Margin:0;color:#8a8a8a;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-weight:500;line-height:1.2;margin:0;padding:0;text-align:left;text-decoration:none">support@cloudradar.io</a><br>
                                                            Dortustraße 46, 14467<br>
                                                            Potsdam, Germany
                                                        </small>
                                                    </p>
                                                </th>
                                                <th class="expander" style="Margin:0;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:400;line-height:1.2;margin:0;padding:0!important;text-align:left;visibility:hidden;width:0"></th></tr></table></th>
                                </tr></tbody></table>
                        </td></tr></tbody></table>
                <table class="spacer float-center" style="Margin:0 auto;border-collapse:collapse;border-spacing:0;float:none;margin:0 auto;padding:0;text-align:center;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top"><td height="16px" style="-moz-hyphens:auto;-webkit-hyphens:auto;Margin:0;border-collapse:collapse!important;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:16px;font-weight:300;hyphens:auto;line-height:16px;margin:0;mso-line-height-rule:exactly;padding:0;text-align:left;vertical-align:top;word-wrap:break-word"></td></tr></tbody></table>
                <table align="center" class="wrapper secondary float-center" style="Margin:0 auto;background:#f3f3f3;border-collapse:collapse;border-spacing:0;float:none;margin:0 auto;padding:0;text-align:center;vertical-align:top;width:100%"><tr style="padding:0;text-align:left;vertical-align:top"><td class="wrapper-inner" style="-moz-hyphens:auto;-webkit-hyphens:auto;Margin:0;border-collapse:collapse!important;color:#182936;font-family:Nunito Sans,Arial,Roboto,Helvetica,sans-serif;font-size:10pt;font-weight:300;hyphens:auto;line-height:1.2;margin:0;padding:0 20px;text-align:left;vertical-align:top;word-wrap:break-word">
                        </td></tr></table>
            </center>
        </td>
    </tr>
</table>
<!-- prevent Gmail on iOS font size manipulation -->
<div style="display:none;white-space:nowrap;font:15px courier;line-height:0"></div>
</body>
</html>
